In [2]:
%reload_ext autoreload
%autoreload 2
from pathlib import Path
import neurokit2 as nk
import numpy as np
import sys
sys.path.append("..")
from feature_extraction import extract_features

root_path = Path("/media/hdd1/i-care/processed/")

In [3]:
# Select one patient to construct the pipeline
p_data = root_path / "0326"

In [21]:
# Loop through the hourly segments of EEG data
for hr_seg in sorted(p_data.iterdir()):
    # Read in the segment
    eeg_data = np.load(hr_seg)
    total_samp = eeg_data.shape[0]
    window_samp = 5*60*100
    # Loop through each segment with a 5 minute window
    for start in range(0, eeg_data.shape[0], window_samp):
        end = start + window_samp
        # Drop segments that don't have full length
        if end <= total_samp:
            segment = eeg_data[start:end, :]
        # Extract features from the segment
        feature = extract_features(segment)
        print(feature)

[0.06077705 0.00876823 0.00613306 0.00657752 0.10091077 4.49152049]
[0.0508732  0.00777823 0.00711168 0.00748702 0.13979222 4.67814405]
[0.14213293 0.06301468 0.01128638 0.01038007 0.07940723 3.1074793 ]
[0.06113815 0.01651502 0.01527845 0.01388126 0.24990045 5.30226146]
[0.06113815 0.01651502 0.01527845 0.01388126 0.24990045 5.30226146]
[0.0407846  0.01285619 0.0127832  0.01160903 0.31343201 5.33254098]
[0.03906658 0.01216991 0.01148744 0.01041152 0.2940478  5.34748916]
[0.05840492 0.02142853 0.01988624 0.01951403 0.34048911 5.1957153 ]
[0.05888782 0.02023021 0.01767149 0.01734412 0.30008743 5.28943316]
[0.06782922 0.02455584 0.02282492 0.02119169 0.33650569 5.21134476]
[0.04192369 0.01770125 0.0172851  0.01718606 0.41229912 5.08387327]
[0.04181273 0.01573125 0.01531894 0.01510856 0.36637039 5.08728135]
[0.04838951 0.01693189 0.01664798 0.01595006 0.34404118 5.20945123]
[0.05603699 0.019863   0.01889781 0.01866042 0.33723813 5.24744157]
[0.06916221 0.02409031 0.0226041  0.02410357 0.3